#!/bin/bash

for var in 1 #3 4 5 6 7 8 10 11
do
					
python Zp_tTp_Treemaker_Config.py -n "QCD_HT300to500" -f "/eos/uscms/store/user/anovak/QCD/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/B2GAnaFW_80X_V2p0_PR53_Aug06_RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/160806_234704/0000/" -p "PileupHistFiller/PU_weights_QCD_HT300to500.root" -x "347700" -c "" -s "/uscms_data/d3/anovak/ZprimeTrees/mc/" |& tee -a outputQCD.txt &


python Zp_tTp_Treemaker_Config.py -n "QCD_HT500to700" -f "/eos/uscms/store/user/anovak/QCD/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/B2GAnaFW_80X_V2p0_PR53_Aug06_RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/160806_234825/0000/" -p "PileupHistFiller/PU_weights_QCD_HT500to700.root" -x "32100" -c "" -s "/uscms_data/d3/anovak/ZprimeTrees/mc/"  |& tee -a outputQCD.txt &


python Zp_tTp_Treemaker_Config.py -n "QCD_HT700to1000" -f "/eos/uscms/store/user/anovak/QCD/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/B2GAnaFW_80X_V2p0_PR53_Aug06_RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/160806_234946/0000/" -p "PileupHistFiller/PU_weights_QCD_HT700to1000.root" -x "6831" -c "" -s "/uscms_data/d3/anovak/ZprimeTrees/mc/"  |& tee -a outputQCD.txt &

python Zp_tTp_Treemaker_Config.py -n "QCD_HT1000to1500" -f "/eos/uscms/store/user/anovak/QCD/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/B2GAnaFW_80X_V2p0_PR53_Aug06_RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v2/160806_235108/0000/" -p "PileupHistFiller/PU_weights_QCD_HT1000to1500.root" -x "1207" -c "" -s "/uscms_data/d3/anovak/ZprimeTrees/mc/"  |& tee -a outputQCD.txt &


python Zp_tTp_Treemaker_Config.py -n "QCD_HT1500to2000" -f "/eos/uscms/store/user/anovak/QCD/QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/B2GAnaFW_80X_V2p0_PR53_Aug06_RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v3/160806_235229/0000/" -p "PileupHistFiller/PU_weights_QCD_HT1500to2000.root" -x "119.9" -c "" -s "/uscms_data/d3/anovak/ZprimeTrees/mc/"  |& tee -a outputQCD.txt &


python Zp_tTp_Treemaker_Config.py -n "QCD_HT2000toInf" -f "/eos/uscms/store/user/anovak/QCD/QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/B2GAnaFW_80X_V2p0_PR53_Aug06_RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/160806_235350/0000/" -p "PileupHistFiller/PU_weights_QCD_HT2000toInf.root" -x "25.24" -c "" -s "/uscms_data/d3/anovak/ZprimeTrees/mc/" |& tee -a outputQCD.txt &

#############################################################

#python Zp_tTp_Treemaker_TEST.py -n "QCD_HT700to1000test" -f "/eos/uscms/store/user/anovak/QCD/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/B2GAnaFW_80X_V2p0_PR53_Aug06_RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/160806_234946/0000/" -p "PileupHistFiller/oldweights/PU_weights_ST_T.root" -w "0.0004372782" -c "" |& tee -a outputQCD.txt

#python Zp_tTp_Treemaker_TEST.py -n "QCD_HT1000to1500test" -f "/eos/uscms/store/user/anovak/QCD/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/B2GAnaFW_80X_V2p0_PR53_Aug06_RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v2/160806_235108/0000/" -p "PileupHistFiller/oldweights/PU_weights_ST_T.root" -w "1" -c "" |& tee -a outputQCD.txt

done

