#!/bin/bash

for var in  0
do
echo "Processing part $var" |& tee -a output.txt

python PileUpCalc.py -n "TT" -f "/eos/uscms/store/user/osherson/80XTrees/ttbar/B2GAnaFW_80X_V2p0_PR53_Aug06_RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0_ext4-v1/160806_233846/"  |& tee -a output.txt

echo "Completed processing part $var" |& tee -a output.txt


done

